version: '3' 

services:

  mariadb:
    container_name : mariadb
    build:
      ./requirements/mariadb
    image: mariadb    
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress:/var/www
    restart: on-failure
    depends_on:
      - wordpress
  
  wordpress:
    container_name: wordpress
    build:
      ./requirements/wordpress
    image: wordpress
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress:/var/www
    restart: on-failure
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/fabperei/wordpress
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/fabperei/mariadb
